### ISSUE TITLE
MoveReadShort and MoveReadUShort are missing?

### ISSUE THREAD

**Issue by StefH** [tedd/Tedd.SpanUtils#11]

**Comment by tedd** [comment]
They are MoveReadInt16 and MoveReadUInt16 respectively. I'll add aliases for Short as well. I was planning to, but forgot along the way. :)

Just a personal preference to use Int16, Int32, Int64 over short, int, long.

**Comment by tedd** [comment]
Added. I see I was already working on that in #1 . (Memory slowly returning after being away a few months due to family increase.)
