### ISSUE TITLE
SpanStream v.s. BinaryReader & BinaryWriter

### ISSUE THREAD

**Issue by StefH** [tedd/Tedd.SpanUtils#12]
Hello @tedd ,

I thought that the `SpanStream` could be used to replace `BinaryReader` and `BinaryWriter`, however this does not work because the byte storing is reversed.

Your code
``` c#
public static UInt32 ReadUInt32(this Span<byte> span)
        {
            // return MemoryMarshal.Cast<byte, UInt32>(span)[0];
            return (UInt32)(
                ((UInt32)span[3])
                | ((UInt32)span[2] << (8 * 1))
                | ((UInt32)span[1] << (8 * 2))
                | ((UInt32)span[0] << (8 * 3))
                );
        }
```

Code from BinaryReader (https://referencesource.microsoft.com/#mscorlib/system/io/binaryreader.cs,185)
``` c#
return (int)(m_buffer[0] | m_buffer[1] << 8 | m_buffer[2] << 16 | m_buffer[3] << 24);
```

Is this intentional?

**Comment by tedd** [comment]
No particular reason, but when you point it out there should probably be little endian by default and maybe support both by some option. I'll look into how to solve it without exploding the codebase. :)

**Comment by tedd** [comment]
I've flipped from big endian to little endian as default, also added excplicit LE and BE as alternative for all methods. Will add unit tests for BinaryReader and BinaryWriter later to ensure it works.

Supporting both endians without adding the overhead of an if-statement to every method by offering excplicit methods for them, i.e. ReadInt32BE.
