### ISSUE TITLE
.netstandard 2.0

### ISSUE THREAD

**Issue by StefH** [tedd/Tedd.SpanUtils#5]
Can you please make your library compatible with .net standard 2.0 ?

**Comment by tedd** [comment]
Sure, no problem. I've committed fix for .Net Standard 2.0 and added to NuGet (as preview/beta package since I have a few things I need to test).
https://www.nuget.org/packages/Tedd.SpanUtils/1.1.0-beta.7

**Comment by StefH** [comment]
Thanks !
