### ISSUE TITLE
SpanStream : Length is set to 0 initially ?

### ISSUE THREAD

**Issue by StefH** [tedd/Tedd.SpanUtils#8]
![image](https://user-images.githubusercontent.com/249938/104087629-78fbb800-5261-11eb-9965-ff9cddaec71e.png)

This looks strange?

I would expect the length to be 3?

**Comment by tedd** [comment]
Good catch. I believe this was done to emulate the behavior of a MemoryStream, except you control the underlying memory by span. But looking at it now it does seem like a bug. 👍

**Comment by tedd** [comment]
Changed to set length to span length. Behavior not consistent with MemoryStream, but more intuitive.
